server:
    port: ${PORT:8080}
spring:
    application:
        name: maru-backend
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${DATABASE_URL}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                show_sql: false
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_SECRET}
                        scope:
                            - profile
                            - email
oauth:
    redirect-url: ${OAUTH_REDIRECT_URL}
    success-url: ${OAUTH_SUCCESS_URL}
jwt:
    access-token:
        secret: ${ACCESS_TOKEN_SECRET}
        expiration: ${ACCESS_TOKEN_EXPIRATION}
    register-token:
        secret: ${REGISTER_TOKEN_SECRET}
        expiration: ${REGISTER_TOKEN_EXPIRATION}
diary:
    secret: ${DIARY_SECRET}
cors:
    origins: ${CORS_ORIGINS}
