name: Check ktlint and Run unit tests
on:
    workflow_dispatch:
    pull_request:
        branches:
            - main

jobs:
    ktlint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the source code.
              uses: actions/checkout@master

            - name: Setup JDK 17
              uses: actions/setup-java@v1
              with:
                  java-version: 17

            - name: Grant execute permission
              run: chmod +x gradlew

            - name: Run tests
              run: ./gradlew ktlintCheck

    unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the source code.
              uses: actions/checkout@master

            - name: Setup JDK 17
              uses: actions/setup-java@v1
              with:
                java-version: 17

            - name: Grant execute permission
              run: chmod +x gradlew

            - name: Run tests
              run: ./gradlew test
